"""
Cutplace version information.
"""
VERSION = 0
RELEASE = 5
REVISION = 8
VERSION_DATE = "2009-10-12"

VERSION_NUMBER = "%d.%d.%d" % (VERSION, RELEASE, REVISION)
VERSION_TAG = "%s (%s)" % (VERSION_NUMBER, VERSION_DATE)
